### ISSUE TITLE
Discover stack name and versions

### ISSUE THREAD

**Issue by vibhory2j** [zalando-zmon/zmon-aws-agent#126]
As a ZMON grafana dashboard user, I would like to see the queryable stack name and version templating option. This would help users in parameterising their dashboards and monitor applications seamlessly for different deployment versions. 

This would require the zmon aws agent to discover the stack names and versions as entities and store them in KairosDB.

**Comment by mohabusama** [comment]
STUPS specific ``stack_name`` and ``stack_version`` are currently handled by the agent and are part of the ``instance`` entity. Why do we need new entity type for stack_name and stack_version?

**Comment by vibhory2j** [comment]
Not explicitly asking for a new entity type unless the requirement can be fulfilled by instance entity itself.

**Comment by mohabusama** [comment]
I believe the requirement is already fulfilled and can be queried in Dashboards.
Closing for now. Please feel free to re-open in case other requirements came up.
