### ISSUE TITLE
Reduce number of AWS API invocations

### ISSUE THREAD

**Issue by Jan-M** [zalando-zmon/zmon-aws-agent#22]
Events per instance does not yield anything interesting so far, strip it.

Dont query for active members of ELB/ASK. Wrap this call in check command, so it is only done if it matters.

**Comment by Jan-M** [comment]
And do not query user_data if instance is already known, basically immutable data for an EC2 instance (?)

**Comment by mohabusama** [comment]
As one of the teams got affected by disabling instance events calls, we need to keep it. #86

**Comment by rajatparida86** [comment]
@mohabusama 
- What is the problem statement here?
- Can this be closed now or we need to work on this?
