### ISSUE TITLE
Number of ASG entities is limited to 50

### ISSUE THREAD

**Issue by dryewo** [zalando-zmon/zmon-aws-agent#31]
I create a check using Trial Run and use this entity filter:

```
[
    {
        "type": "asg",
        "infrastructure_account": "aws:1234567890123"
    }
]
```

When I run the check, it returns 50 results, although there are 88 ASGs in the account. If I remove the `infrastructure_account` constraint, I get more than a 1000 results (all ASGs from all the accounts).

I expect to get all matching ASGs when I use `infrastructure_account` filter, not only first 50.

**Comment by hjacobs** [comment]
To be fixed: we are only reading the first page of results from AWS API.
