### ISSUE TITLE
use stack_version instead of application_version

### ISSUE THREAD

**Issue by Jan-M** [zalando-zmon/zmon-aws-agent#41]
As we no longer enforce new application versions, entity ids become hard to read.

I dont even know why this was ever done differently :D (blaming myself)

**Comment by Jan-M** [comment]
![image](https://cloud.githubusercontent.com/assets/1443395/17344093/37e22bb4-5901-11e6-942e-a6bbe114ac0a.png)

Maybe even use stack_name and stack_version. Screenshot sows two stacks. And we even have scenarios where two stack names have same application id.

@hjacobs thoughts on this?

**Comment by hjacobs** [comment]
:+1: for using `stack_version`.

I'm not sure whether we should use `stack_name` instead of `application_id` as the application ID is globally unique and the stack_name is not.
