### ISSUE TITLE
Add automated unit tests / flake8 checking

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-aws-agent#5]
As we are getting pull requests, we should add automated tests on Travis CI + flake8 checking.

**Comment by marek-obuchowicz** [comment]
`/run.sh` which is docker `CMD` is running zmon-agent with python 2, so I think we should use the same python version on Travis CI

**Comment by hjacobs** [comment]
We should also add a coverage provider (codecov or coveralls) and badges :-)
