### ISSUE TITLE
Support Application Load Balancer (ELBv2)

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-aws-agent#50]
Required to support https://github.com/zalando-stups/senza/issues/310

**Comment by mohabusama** [comment]
For the sake of documenting the diff between elbv2 and elb "classic", some changes are required.

- We might need to generate ``entity['name']`` to match the one needed by  [Cloudwatch dimension](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/elb-metricscollected.html#load-balancer-metrics-alb)
- ELB Health is defined by ``TargetGroups``, that will require extra API call(s) to retrieve target groups and target groups health.
- Add ``elb_type`` (or ``elb_version``) to identify difference between both ELBs.
- Cloudwatch checks will need to be aware of target ELB version, (``LoadBalancerName`` vs ``LoadBalancer`` ...) in dimensions and (``HTTPCode_Target_2XX_Count`` vs ``HTTPCode_Backend_2XX`` ...) in metrics.
- Determining ``dns_traffic`` and ``dns_weight`` still not clear.

**Comment by hjacobs** [comment]
@mohabusama your points are valid, to clarify the last one: DNS traffic switching works exactly the same for ELBv2, so going through DNS records and checking their weight (and alias target) should work for ELBv1 and ELBv2.
