### ISSUE TITLE
Sync spot instance price

### ISSUE THREAD

**Issue by mohabusama** [zalando-zmon/zmon-aws-agent#89]
Could be useful to return Spot instance price (may be as a separate entity), this would help in alerting if spot instances are being used.

- Should be optional

**Comment by Jan-M** [comment]
Can this not be monitored using AWS cloudwatch?

**Comment by mohabusama** [comment]
From my understanding, it is in ``ec2`` scope http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-spot-price-history.html

and in Boto3 http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.describe_spot_price_history

**Comment by Jan-M** [comment]
Then this should be enabled/disabled. We should be fine tracking this via entities in a single account per region i guess.

**Comment by mfelsche** [comment]
:+1:
